<?php /* Smarty version 2.6.20, created on 2014-07-02 13:46:47
         compiled from header.tpl */

$this->_cache_serials['C:\WampDeveloper\Websites\exe.ir\webroot/include/Smarty/templates_c\%%F7^F7F^F7F34188%%header.tpl.inc'] = '25a6008b63b7f76a59cdfd174e81786e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'smarty_fewchars', 'header.tpl', 90, false),array('function', 'dropdown_menu_video_categories', 'header.tpl', 266, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 274, false),)), $this); ?>
<?php
function _smarty_tplfunc_25a6008b63b7f76a59cdfd174e81786e_0(&$_smarty)
{
echo smarty_art_html_list_categories(array('max_levels' => 3), $_smarty);
}



?>
